### ISSUE TITLE
Import error when using version 1.0.3

### ISSUE THREAD

**Issue by asdrubalivan** [sendbird/sendbird-platform-sdk-python#1]
Hello everyone I'm getting this error using SDK's version `1.0.3`  after running the example that's shown on the README

```
Traceback (most recent call last):
  File "/home/asdru/work/company/service/app/manage.py", line 19, in <module>
    manager.run()
  File "/home/asdru/.cache/pypoetry/virtualenvs/service-COZteKYw-py3.10/lib/python3.10/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/home/asdru/.cache/pypoetry/virtualenvs/service-COZteKYw-py3.10/lib/python3.10/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/home/asdru/.cache/pypoetry/virtualenvs/service-COZteKYw-py3.10/lib/python3.10/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/asdru/work/company/service/app/service/__init__.py", line 75, in call_sendbird_api
    call_api()
  File "/home/asdru/work/company/service/app/service/utils/sendbird.py", line 11, in call_api
    api_instance = user_api.UserApi(api_client)
  File "/home/asdru/.cache/pypoetry/virtualenvs/service-COZteKYw-py3.10/lib/python3.10/site-packages/sendbird_platform_sdk/api/user_api.py", line 210, in __init__
    'response_type': (CreateChannelMetacounterResponse,),
NameError: name 'CreateChannelMetacounterResponse' is not defined. Did you mean: 'CreateChannelMetadataResponse'?
```

For reference purposes this is the example

```python
    with sendbird_platform_sdk.ApiClient(configuration=configuration) as api_client:
        api_instance = user_api.UserApi(api_client)
        api_token = os.environ["SENDBIRD_API_TOKEN"]

        try:
            api_response = api_instance.list_users(api_token=api_token, limit=1)
            pprint(api_response)
        except sendbird_platform_sdk.ApiException as e:
            print("Exception when calling UserApi->list_users: %s\n" % e)
```

Note that I can run the example by using version `1.0.0`

**Comment by james-a-rob** [comment]
Hi @asdrubalivan

Thanks for raising this issue. I have taken a look into it for you.

As a little context, the core of this SDK is generated from a YAML Open API spec file. A recent schema change has caused the Python SDK to throw this error. I am have located the issue, fixed the problem and I am now currently just performing so testing on our side to make sure everything is now working.

All being well, I will release version 1.0.4 of this SDK release in the next few hours.

**Comment by james-a-rob** [comment]
New release of the SDK to fix your issue.

https://github.com/sendbird/sendbird-platform-sdk-python/releases/tag/1.0.5

Please feel free to let me know if you encounter any problems.
